version: '3'

services:
  web:
    build: .
    command: granian --interface asgi --host 0.0.0.0 --port 7000 core.asgi:application
    volumes:
      - .:/code
      - ./static:/code/static  # Mount the static folder
      - ./media:/code/media  # Mount the media folder if you have one
    ports:
      - "7000:7000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DEBUG=False