version: '3'

services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:7000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - "7000:7000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings

volumes:
  static_volume:
  media_volume: