version: '3'

services:
  web:
    build: .
    command: granian --interface wsgi --host 0.0.0.0 --port 7000 core.wsgi:application
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "7000:7000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DEBUG=False

volumes:
  static_volume:
  media_volume: