# Use an official Python runtime as a parent image
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install dependencies
COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Install Granian with reload extra
RUN pip install "granian[reload]"

# Copy project
COPY . /code/

# Run the application
CMD ["granian", "--interface", "wsgi", "--host", "0.0.0.0", "--port", "8000", "--reload", "core.wsgi:application"]