version: '3'

services:
  web:
    build: .
    command: granian --interface wsgi --host 0.0.0.0 --port 7000 core.wsgi:application
    volumes:
      - .:/code
      - /home/rahmat/viollence/static:/code/static
      - /home/rahmat/viollence/media:/code/media
    ports:
      - "7000:7000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DEBUG=False