version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /Users/pro/Work/violence/static:/code/static
      - /Users/pro/Work/violence/media:/code/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DEBUG=True
