version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: granian --interface wsgi --host 0.0.0.0 --port 8000 --reload core.wsgi:application
    volumes:
      - .:/code
      - /Users/pro/Work/violence/static:/code/static
      - /Users/pro/Work/violence/media:/code/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DEBUG=True