version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:7000 core.wsgi:application
    volumes:
      - .:/code
      - /home/rahmat/viollence/static:/code/static
      - /home/rahmat/viollence/media:/code/media
    ports:
      - "7000:7000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DEBUG=False