# Generated by Django 5.0.6 on 2024-07-24 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(default='', editable=False, max_length=550)),
                ('keterangan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=10)),
                ('incident_date', models.DateField()),
                ('image', models.ImageField(upload_to='incidents/')),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('coder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_coded', to=settings.AUTH_USER_MODEL)),
                ('incident_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_relations', to='web.incidents')),
                ('verificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidents',
                'verbose_name_plural': 'Incident',
            },
        ),
        migrations.CreateModel(
            name='Casualities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_death', models.PositiveIntegerField(default='0')),
                ('num_injured', models.PositiveIntegerField(default='0')),
                ('death_injured', models.PositiveIntegerField(default='0')),
                ('female_death', models.PositiveIntegerField(default='0')),
                ('female_injured', models.PositiveIntegerField(default='0')),
                ('female_total', models.PositiveIntegerField(default='0')),
                ('child_death', models.PositiveIntegerField(default='0')),
                ('child_injured', models.PositiveIntegerField(default='0')),
                ('child_total', models.PositiveIntegerField(default='0')),
                ('infra_damage', models.PositiveIntegerField(default='0')),
                ('infra_destroyed', models.PositiveIntegerField(default='0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incident_casualities', to='web.incidents')),
            ],
            options={
                'verbose_name': 'Casualities',
                'verbose_name_plural': 'Casuality',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(default='', editable=False, max_length=550)),
                ('img', models.ImageField(blank=True, upload_to='option/')),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Intervene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incident_intervene', to='web.incidents')),
                ('intervene_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.options')),
                ('intervene_actor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervene_type', to='web.options')),
            ],
            options={
                'verbose_name': 'Intervene',
                'verbose_name_plural': 'Intervene',
            },
        ),
        migrations.AddField(
            model_name='incidents',
            name='category',
            field=models.ManyToManyField(limit_choices_to={'category': 2}, related_name='Violence_category', to='web.options'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minorities', models.BooleanField(default=False)),
                ('total_actor', models.IntegerField(default='-99')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incident_id', to='web.incidents')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_actor', to='web.options')),
                ('actor_atribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_actor', to='web.options')),
            ],
            options={
                'verbose_name': 'Actors',
                'verbose_name_plural': 'Actor',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=100, null=True)),
                ('area_code', models.PositiveIntegerField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'category': 1}, on_delete=django.db.models.deletion.CASCADE, to='web.options')),
                ('parents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_provinces', to='web.regions')),
            ],
            options={
                'verbose_name': 'Provinisi/Kabupaten/Kota',
                'verbose_name_plural': 'Provinisi/Kabupaten/Kota',
            },
        ),
        migrations.AddField(
            model_name='incidents',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_loc', to='web.regions'),
        ),
        migrations.CreateModel(
            name='Violence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Incident_violence', to='web.incidents')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_type_violence', to='web.options')),
                ('violence_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_violence', to='web.options')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_type_violence', to='web.options')),
            ],
            options={
                'verbose_name': 'Violences',
                'verbose_name_plural': 'Violence',
            },
        ),
    ]
