# Generated by Django 5.0.6 on 2024-07-25 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_actor_actor_alter_actor_actor_atribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violence',
            name='issue_type',
            field=models.ForeignKey(limit_choices_to={'category': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='issue_type_violence', to='web.options'),
        ),
        migrations.AlterField(
            model_name='violence',
            name='violence_form',
            field=models.ForeignKey(limit_choices_to={'category': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='form_violence', to='web.options'),
        ),
        migrations.AlterField(
            model_name='violence',
            name='weapon_type',
            field=models.ForeignKey(limit_choices_to={'category': 6}, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_type_violence', to='web.options'),
        ),
    ]
