# Generated by Django 5.0.6 on 2024-07-25 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_violence_issue_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervene',
            name='intervene_actor',
            field=models.ForeignKey(limit_choices_to={'category': 7}, on_delete=django.db.models.deletion.CASCADE, to='web.options'),
        ),
        migrations.AlterField(
            model_name='intervene',
            name='intervene_actor_type',
            field=models.ForeignKey(limit_choices_to={'category': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='intervene_type', to='web.options'),
        ),
    ]
