# Generated by Django 5.0.6 on 2024-07-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_intervene_intervene_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
