# Generated by Django 5.0.6 on 2024-07-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_incidents_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Statistics', to='web.options')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Statistics_satuan', to='web.options')),
            ],
            options={
                'verbose_name': 'Data Name',
                'verbose_name_plural': 'Data Name',
            },
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.dataname')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.regions')),
            ],
            options={
                'verbose_name': 'Data Value',
                'verbose_name_plural': 'Data Value',
            },
        ),
    ]
