# Generated by Django 5.0.6 on 2024-07-27 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_dataname_datavalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataname',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category': 9}, on_delete=django.db.models.deletion.CASCADE, related_name='Statistics', to='web.options'),
        ),
        migrations.AlterField(
            model_name='dataname',
            name='satuan',
            field=models.ForeignKey(limit_choices_to={'category': 8}, on_delete=django.db.models.deletion.CASCADE, related_name='Statistics_satuan', to='web.options'),
        ),
    ]
