# Generated by Django 5.0.6 on 2024-07-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_dataname_category_alter_dataname_satuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataname',
            name='sumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
