# Generated by Django 5.0.6 on 2024-07-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_dataname_keterangan_dataname_sumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataname',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=550),
        ),
    ]
