# Generated by Django 4.2 on 2024-08-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_dataname_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incidents/'),
        ),
    ]
