# Generated by Django 4.2 on 2024-08-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_incidents_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
