# Generated by Django 4.2 on 2024-08-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_incidents_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_date',
            field=models.DateField(),
        ),
    ]
