# Generated by Django 4.2 on 2024-08-23 05:39

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_incidents_incident_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(default='', editable=False, max_length=550)),
                ('img_cover', models.ImageField(blank=True, upload_to='publications/cover/')),
                ('img_credit', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='publications/doc/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_count', models.PositiveIntegerField(default=0)),
                ('publish', models.BooleanField(default=False)),
                ('category', models.ForeignKey(limit_choices_to={'category': 5}, on_delete=django.db.models.deletion.CASCADE, to='web.options')),
            ],
            options={
                'verbose_name': 'Publications',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
