# Generated by Django 4.2 on 2024-08-23 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category': 10}, on_delete=django.db.models.deletion.CASCADE, to='web.options'),
        ),
    ]
