# Generated by Django 4.2 on 2024-08-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_publications_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publications',
            options={},
        ),
    ]
