# Generated by Django 4.2 on 2024-08-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_publications_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publications',
            options={'verbose_name': 'Publications', 'verbose_name_plural': 'Publications'},
        ),
    ]
