# Generated by Django 4.2 on 2024-08-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_publications_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='incident_id',
            field=models.CharField(max_length=20),
        ),
    ]
